library(topsis)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
library(ggrepel)

resort <- read_excel("C:/Users/cmuro/Downloads/dataresort.xlsx")
View(resort)
w <- c(0.11,0.11,0.05,0.11,0.11,0.07,0.07,0.09,0.07,0.11,0.1) 
i <- c("+","+","+","+","+","+","+","+","+","+","+")
sum(w)

datare <- select(resort,8:18)
nm <- data.matrix(datare)
View(resort[,1])
results <- topsis(nm,w,i)
results <- data.matrix(results)
class(results)
final <- cbind.data.frame(resort[,1],results)
View(final)
